@startuml nist-standard-document
/'
Diagram:        NistStandardDocument
DateCreate:     22/08/2018
Description:    Metanorma IsoDoc is a family of document models intended to represent ISO Standards and similarly structured standards,
                based on the Metanorma StandardDocument ("StanDoc") and BasicDocument ("BasicDoc") models.
                It is used to abstract the automated generation of standard documents in various formats from well-defined authoring tools;
                and to validate the structural conformance of authored standards to specifications.
'/

'******* CONFIGURATION ************************************************
!include style.uml.inc


'******* CLASS DEFINITION *********************************************
class StandardDocument <<StandardDocument>> {

}

class NistStandardDocument {
  +bibdata: NistBibliographicItem
  +preface: Preface[0..1]
  +sections: ClauseSection[1..*]
  +annex: AnnexSection[0..*]
}

class Preface {
  +abstract: HierarchicalSection[0..1],
  +authority: Authority,
  +foreword: HierarchicalSection[0..1],
  +clause: HierarchicalSection[0..*],
  +reviewernote: HierarchicalSection[0..1],
  +executivesummary: HierarchicalSection[0..1],
}

class Authority {
  +authority1: StandardSection,
  +authority2: StandardSection,
  +authority3: StandardSection,
  +authority4: StandardSection,
  +authority5: StandardSection
}


class TextElement <<BasicDoc>>{

}

class Keyword {

}

class IdElement <<BasicDoc>>{

}

class Figure{
    +source: String[0..1]
    +name: LocalizedString[0..1]
    +note: ParagraphWithFootnote[0..*]
    +figure: Figure[0..*]
    +definitions: DefinitionList[0..1]
    +pre: String[0..1]
    +content: TextElement[0..*]
}

'******* NOTES ********************************************************
note right of NistStandardDocument: The first section is titled "Introduction".



'******* CLASS RELATIONS **********************************************
StandardDocument <-- NistStandardDocument
NistStandardDocument <-- Preface
Preface <-- Authority

TextElement <-- Keyword

IdElement <-- Figure

@enduml
